name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    -  run: docker build . -t thaslifa/mygitaction
      -run:  echo "${{secrets.DOCKERHUB_PASSWORD}}"  |docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push thaslifa/mygitaction:latest
